# 18 jobs 
sweep:
# cosines first
  - device_train_microbatch_size: 32
    save_interval_unsharded: 625
    global_train_batch_size: 512
    num_passes: 1
    wandb:
      group: fixed_300m_16x_chinchilla 
    optimizer:
      name: adamw
      learning_rate: [3.0e-4, 1.0e-3, 3.0e-3]
      beta_0: 0.9
      beta_1: [0.95, 0.99]
      eps: 1.0e-8
      decouple_weight_decay: false
      weight_decay: 0.0
      decay_norm_and_bias: true
      decay_embeddings: true
      metrics_log_interval: 100
    model:
      use_ema: false
    scheduler:
      name: "cosine_with_warmup"
      t_warmup: 5000
    max_duration: 12500 
    stop_at: 12500 #1x chinchilla
  - device_train_microbatch_size: 32
    save_interval_unsharded: 1250
    global_train_batch_size: 512
    num_passes: 1
    wandb:
      group: fixed_300m_16x_chinchilla 
    optimizer:
      name: adamw
      learning_rate: [3.0e-4, 1.0e-3, 3.0e-3]
      beta_0: 0.9
      beta_1: [0.95, 0.99]
      eps: 1.0e-8
      decouple_weight_decay: false
      weight_decay: 0.0
      decay_norm_and_bias: true
      decay_embeddings: true
      metrics_log_interval: 100
    model:
      use_ema: false
    scheduler:
      name: "cosine_with_warmup"
      t_warmup: 5000
    max_duration: 25000 
    stop_at: 25000 #2x chinchilla
  - device_train_microbatch_size: 32
    save_interval_unsharded: 2500
    global_train_batch_size: 512
    num_passes: 1
    wandb:
      group: fixed_300m_16x_chinchilla 
    optimizer:
      name: adamw
      learning_rate: [3.0e-4, 1.0e-3, 3.0e-3]
      beta_0: 0.9
      beta_1: [0.95, 0.99]
      eps: 1.0e-8
      decouple_weight_decay: false
      weight_decay: 0.0
      decay_norm_and_bias: true
      decay_embeddings: true
      metrics_log_interval: 100
    model:
      use_ema: false
    scheduler:
      name: "cosine_with_warmup"
      t_warmup: 5000
    max_duration: 50000 
    stop_at: 50000 #4x chinchilla
  - device_train_microbatch_size: 32
    save_interval_unsharded: 5000
    global_train_batch_size: 512
    num_passes: 1
    wandb:
      group: fixed_300m_16x_chinchilla 
    optimizer:
      name: adamw
      learning_rate: [3.0e-4, 1.0e-3, 3.0e-3]
      beta_0: 0.9
      beta_1: [0.95, 0.99]
      eps: 1.0e-8
      decouple_weight_decay: false
      weight_decay: 0.0
      decay_norm_and_bias: true
      decay_embeddings: true
      metrics_log_interval: 100
    model:
      use_ema: false
    scheduler:
      name: "cosine_with_warmup"
      t_warmup: 5000
    max_duration: 100000 
    stop_at: 100000 #8x chinchilla
  - device_train_microbatch_size: 32
    save_interval_unsharded: 10000
    global_train_batch_size: 512
    num_passes: 1
    wandb:
      group: fixed_300m_16x_chinchilla 
    optimizer:
      name: adamw
      learning_rate: [3.0e-4, 1.0e-3, 3.0e-3]
      beta_0: 0.9
      beta_1: [0.95, 0.99]
      eps: 1.0e-8
      decouple_weight_decay: false
      weight_decay: 0.0
      decay_norm_and_bias: true
      decay_embeddings: true
      metrics_log_interval: 100
    model:
      use_ema: false
    scheduler:
      name: "cosine_with_warmup"
      t_warmup: 5000
    max_duration: 200000 
    stop_at: 200000 #16x chinchilla
  #constant w avg
  - device_train_microbatch_size: 32
    global_train_batch_size: 512
    wandb:
      group: fixed_300m_16x_chinchilla
    optimizer:
      name: adamw
      learning_rate: [3.0e-4, 1.0e-3, 3.0e-3]
      beta_0: 0.9
      beta_1: [0.95, 0.99]
      eps: 1.0e-8
      decouple_weight_decay: false
      weight_decay: 0.0
      decay_norm_and_bias: true
      decay_embeddings: true
      metrics_log_interval: 100
    model:
      use_ema: true
    scheduler:
      name: 'constant_with_warmup'
      t_warmup: 5000
    max_duration: 200000
    stop_at: 200000 #16x chinchilla
#sqrt runs
  - device_train_microbatch_size: 32
    global_train_batch_size: 512
    wandb:
      group: fixed_300m_16x_chinchilla
    optimizer:
      name: adamw
      learning_rate: [3.0e-4, 1.0e-3, 3.0e-3]
      beta_0: 0.9
      beta_1: [0.95, 0.99]
      eps: 1.0e-8
      decouple_weight_decay: false
      weight_decay: 0.0
      decay_norm_and_bias: true
      decay_embeddings: true
      metrics_log_interval: 100
    model:
      use_ema: true
    scheduler:
      name: ['inverse_sqrt_with_warmup']
      t_warmup: 5000
      offset: [12_800, 25_600, 51_200]
    max_duration: 200_000
    stop_at: 200_000 #16x chinchilla