# 18 jobs 
sweep:
#cosines
  # - device_train_microbatch_size: 32
  #   num_passes: 1
  #   global_train_batch_size: 4096
  #   wandb:
  #     group: 4k_bsz
  #   optimizer:
  #     name: adamw
  #     learning_rate: [1.0e-3, 3.0e-3, 1.0e-2]
  #     beta_0: 0.9
  #     beta_1: [0.95, 0.99]
  #     eps: 1.0e-8
  #     decouple_weight_decay: false
  #     weight_decay: 0.0
  #     decay_norm_and_bias: true
  #     decay_embeddings: true
  #     metrics_log_interval: 100
  #   model:
  #     use_ema: false 
  #   scheduler:
  #     name: "cosine_with_warmup"
  #     t_warmup: 500
  #   max_duration: 782
  #   stop_at: 782 #1x chinchilla
  # - device_train_microbatch_size: 32
  #   num_passes: 1
  #   global_train_batch_size: 4096
  #   wandb:
  #     group: 4k_bsz
  #   optimizer:
  #     name: adamw
  #     learning_rate: [1.0e-3, 3.0e-3, 1.0e-2]
  #     beta_0: 0.9
  #     beta_1: [0.95, 0.99]
  #     eps: 1.0e-8
  #     decouple_weight_decay: false
  #     weight_decay: 0.0
  #     decay_norm_and_bias: true
  #     decay_embeddings: true
  #     metrics_log_interval: 100
  #   model:
  #     use_ema: false
  #   scheduler:
  #     name: "cosine_with_warmup"
  #     t_warmup: 500
  #   max_duration: 1564
  #   stop_at: 1564 #2x chinchilla
  - device_train_microbatch_size: 32
    num_passes: 1
    global_train_batch_size: 4096
    wandb:
      group: 4k_bsz
    optimizer:
      name: adamw
      learning_rate: [1.0e-3, 3.0e-3, 1.0e-2]
      beta_0: 0.9
      beta_1: [0.95, 0.99]
      eps: 1.0e-8
      decouple_weight_decay: false
      weight_decay: 0.0
      decay_norm_and_bias: true
      decay_embeddings: true
      metrics_log_interval: 100
    model:
      use_ema: false
    scheduler:
      name: "cosine_with_warmup"
      t_warmup: 500
    max_duration: 3128
    stop_at: 3128 #4x chinchilla
  - device_train_microbatch_size: 32
    num_passes: 1
    global_train_batch_size: 4096
    wandb:
      group: 4k_bsz
    optimizer:
      name: adamw
      learning_rate: [1.0e-3, 3.0e-3, 1.0e-2]
      beta_0: 0.9
      beta_1: [0.95, 0.99]
      eps: 1.0e-8
      decouple_weight_decay: false
      weight_decay: 0.0
      decay_norm_and_bias: true
      decay_embeddings: true
      metrics_log_interval: 100
    model:
      use_ema: false
    scheduler:
      name: "cosine_with_warmup"
      t_warmup: 500
    max_duration: 6256
    stop_at: 6256 #8x chinchilla
  - device_train_microbatch_size: 32
    num_passes: 1
    global_train_batch_size: 4096
    wandb:
      group: 4k_bsz
    optimizer:
      name: adamw
      learning_rate: [1.0e-3, 3.0e-3, 1.0e-2]
      beta_0: 0.9
      beta_1: [0.95, 0.99]
      eps: 1.0e-8
      decouple_weight_decay: false
      weight_decay: 0.0
      decay_norm_and_bias: true
      decay_embeddings: true
      metrics_log_interval: 100
    model:
      use_ema: false
    scheduler:
      name: "cosine_with_warmup"
      t_warmup: 500
    max_duration: 12_512
    stop_at: 12_512 #16x chinchilla
  - device_train_microbatch_size: 32
    num_passes: 1
    global_train_batch_size: 4096
    wandb:
      group: 4k_bsz
    optimizer:
      name: adamw
      learning_rate: [1.0e-3, 3.0e-3, 1.0e-2]
      beta_0: 0.9
      beta_1: [0.95, 0.99]
      eps: 1.0e-8
      decouple_weight_decay: false
      weight_decay: 0.0
      decay_norm_and_bias: true
      decay_embeddings: true
      metrics_log_interval: 100
    model:
      use_ema: true
    scheduler:
      name: "constant_with_warmup"
      t_warmup: 500
    max_duration: 12_512 
    stop_at: 12_512 #16x chinchilla
  - device_train_microbatch_size: 32
    global_train_batch_size: 4096
    wandb:
      group: 4k_bsz
    optimizer:
      name: adamw
      learning_rate: [1.0e-3, 3.0e-3, 1.0e-2]
      beta_0: 0.9
      beta_1: [0.95, 0.99]
      eps: 1.0e-8
      decouple_weight_decay: false
      weight_decay: 0.0
      decay_norm_and_bias: true
      decay_embeddings: true
      metrics_log_interval: 100
    model:
      use_ema: true
    scheduler:
      name: 'inverse_sqrt_with_warmup'
      t_warmup: 500
      offset: [800, 1600, 3200, 6400]
    max_duration: 12_512
    stop_at: 12_512 #16x chinchilla