# 18 jobs 
sweep:
  - device_train_microbatch_size: 32
    num_passes: 1
    global_train_batch_size: 4096
    wandb:
      group: 4M_batch_size_fixed
    optimizer:
      name: adamw
      learning_rate: [3.0e-3, 1.0e-2, 3.0e-2]
      beta_0: 0.9
      beta_1: [0.95, 0.98]
      eps: 1.0e-8
      decouple_weight_decay: false
      weight_decay: 0.0
      decay_norm_and_bias: true
      decay_embeddings: true
      metrics_log_interval: 100
    model:
      use_ema: true 
    scheduler:
      name: "cosine_with_warmup"
      t_warmup: 312
    max_duration: 782
    stop_at: 782 #1x chinchilla
  - device_train_microbatch_size: 32
    num_passes: 1
    global_train_batch_size: 4096
    wandb:
      group: 4M_batch_size_fixed
    optimizer:
      name: adamw
      learning_rate: [3.0e-3, 1.0e-2, 3.0e-2]
      beta_0: 0.9
      beta_1: [0.95, 0.98]
      eps: 1.0e-8
      decouple_weight_decay: false
      weight_decay: 0.0
      decay_norm_and_bias: true
      decay_embeddings: true
      metrics_log_interval: 100
    model:
      use_ema: true
    scheduler:
      name: "cosine_with_warmup"
      t_warmup: 312
    max_duration: 1564
    stop_at: 1564 #2x chinchilla
  - device_train_microbatch_size: 32
    num_passes: 1
    global_train_batch_size: 4096
    wandb:
      group: 4M_batch_size_fixed
    optimizer:
      name: adamw
      learning_rate: [3.0e-3, 1.0e-2, 3.0e-2]
      beta_0: 0.9
      beta_1: [0.95, 0.98]
      eps: 1.0e-8
      decouple_weight_decay: false
      weight_decay: 0.0
      decay_norm_and_bias: true
      decay_embeddings: true
      metrics_log_interval: 100
    model:
      use_ema: true
    scheduler:
      name: "cosine_with_warmup"
      t_warmup: 312
    max_duration: 3128
    stop_at: 3128 #4x chinchilla
  - device_train_microbatch_size: 32
    num_passes: 1
    global_train_batch_size: 4096
    wandb:
      group: 4M_batch_size_fixed
    optimizer:
      name: adamw
      learning_rate: [3.0e-3, 1.0e-2, 3.0e-2]
      beta_0: 0.9
      beta_1: [0.95, 0.98]
      eps: 1.0e-8
      decouple_weight_decay: false
      weight_decay: 0.0
      decay_norm_and_bias: true
      decay_embeddings: true
      metrics_log_interval: 100
    model:
      use_ema: true
    scheduler:
      name: "cosine_with_warmup"
      t_warmup: 312
    max_duration: 6256
    stop_at: 6256 #8x chinchilla