# 18 jobs 
sweep:
  - device_train_microbatch_size: 32
    num_passes: 1
    wandb:
      group: second_sweep_cosine
    optimizer:
      name: adamw
      learning_rate: [1.0e-3, 3.0e-3, 1.0e-2]
      beta_0: 0.9
      beta_1: [0.95, 0.98, 0.99]
      eps: 1.0e-8
      decouple_weight_decay: false
      weight_decay: 0.0
      decay_norm_and_bias: true
      decay_embeddings: true
      metrics_log_interval: 100
    model:
      use_ema: false
    scheduler:
      name: "cosine_with_warmup"
      t_warmup: 5000 
    max_duration: 12500
    stop_at: 12500 #1x chinchilla
  - device_train_microbatch_size: 32
    num_passes: 1
    wandb:
      group: second_sweep_cosine 
    optimizer:
      name: adamw
      learning_rate: [1.0e-3, 3.0e-3, 1.0e-2]
      beta_0: 0.9
      beta_1: [0.95, 0.98, 0.99]
      eps: 1.0e-8
      decouple_weight_decay: false
      weight_decay: 0.0
      decay_norm_and_bias: true
      decay_embeddings: true
      metrics_log_interval: 100
    model:
      use_ema: false
    scheduler:
      name: "cosine_with_warmup"
      t_warmup: 5000
    max_duration: 25000
    stop_at: 25000 #2x chinchilla
  - device_train_microbatch_size: 32
    num_passes: 1
    wandb:
      group: second_sweep_cosine 
    optimizer:
      name: adamw
      learning_rate: [1.0e-3, 3.0e-3, 1.0e-2]
      beta_0: 0.9
      beta_1: [0.95, 0.98, 0.99]
      eps: 1.0e-8
      decouple_weight_decay: false
      weight_decay: 0.0
      decay_norm_and_bias: true
      decay_embeddings: true
      metrics_log_interval: 100
    model:
      use_ema: false
    scheduler:
      name: "cosine_with_warmup"
      t_warmup: 5000
    max_duration: 50000
    stop_at: 50000 #4x chinchilla
  - device_train_microbatch_size: 32
    num_passes: 1
    wandb:
      group: second_sweep_cosine 
    optimizer:
      name: adamw
      learning_rate: [1.0e-3, 3.0e-3, 1.0e-2]
      beta_0: 0.9
      beta_1: [0.95, 0.98, 0.99]
      eps: 1.0e-8
      decouple_weight_decay: false
      weight_decay: 0.0
      decay_norm_and_bias: true
      decay_embeddings: true
      metrics_log_interval: 100
    model:
      use_ema: false
    scheduler:
      name: "cosine_with_warmup"
      t_warmup: 5000
    max_duration: 100000
    stop_at: 100000 #8x chinchilla

